remote_theme: pages-themes/cayman@v0.2.0

title: Hey there! I am Poulami Sinhamahapatra
description: Researcher in Computer Vision and Safe AI
author: Poulami Sinhamahapatra
show_excerpts: false

profile_picture: /profile_web.jpg # or /images/profile_web.jpg

github_username: PoulamiSM
linkedin_username: poulami-sinhamahapatra
